### ISSUE TITLE
Automatically remove items from mod-alerts if the user is moderated using RDSS

### ISSUE THREAD

**Issue by Visualizememe** [iamysko/cds#53]
**The Issue**
We have mod-alerts to respond to community members' reports, however, if we're already present in the chat and take action on the user almost immediately - if someone managed to report the user's message right before we took action - we still have to clear the reports in \#mod-alerts against the user.

Just to clarify what I mean:

A supervisor is watching the chat, user 1 posts an inappropriate message, user 2 reacts with the alert_mods reaction and a report is posted in \#mod-alerts, the supervisor takes action with the quick-mute reaction, but the report in \#mod-alerts is not removed.

In mod-alerts, the report against User 1 will still exist even though it's already been handled, and the supervisor doesn't know it, and so there's an already-handled report in \#mod-alerts.

**The Solution**
Automatically remove all reports against the quick-muted users from mod-alerts when the handled users are being moderated through RDSS.

**Consideration**
This might require significant work to be implemented, and it's not really an issue how the system works right now.

**Comment by misterveiga** [comment]
Considering this is live chat, this scenario could be minimized with a delay, followed by a check for the message's existence, before registering the alert.

**Comment by Luitrixx** [comment]
**Just an addition to this issue.**

Whenever a message is deleted by a mod and it's on the #mod-alerts channel, It would be more efficient to also clear out the mod alert as it's handled.

This way the #mod-alerts channel would even be more cleaner and up-to date as you would not need to scroll through old reports and make it easy to deal with new reports.

**Caution**
Only clear the message if it was handled by a mod.
This might be hard and complicated to pull off as discord does not provide the user who deleted the message  but it's possible as you can find this info on the actual server log.

If you end up taking this additional suggestion into consideration but you can't seem to figure out how to get the user who deleted the message, Ping me or reply on here and I will be able to explain further.
